# 1.Write a Python program to add elements to a list using insert() and append().
# my_list = [10, 20, 30]
# my_list.append(40)
# my_list.insert(1, 15)
# print(my_list)

# 2.Write a Python program to remove elements from a list using pop() and remove().
# my_list = [10, 20, 30, 40, 50]
# my_list.remove(30)
# my_list.pop(2)
# print(my_list)

# Practical Example
# 1.Write a Python program to update a list using insert() 
# my_list = [10, 20, 40, 50]
# my_list.insert(2, 30)
# print(my_list)

# 2.Write a Python program to remove elements from a list using pop() and remove()
# my_list = [10, 20, 30, 40, 50]
# my_list.remove(30)
# my_list.pop(2)
# print(my_list)



